// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evxwmidttnfcwkalqxau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2eHdtaWR0dG5mY3drYWxxeGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDc0MzYsImV4cCI6MjA4ODcyMzQzNn0.zVIB9jIuQp8YihCe45CZ5nUsjmEWKsPWbmnA196InLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});